### PR TITLE
Minor v5 cleanup

### PR DESCRIPTION
**Pull request by m5o**
minor cleanup after the bootstrap v5 update. 
I've noticed an issue with the `input_group` and rounded borders

* remove static id attributes
* simplify application.scss
  * import bootstrap library
  * reduce maintenance
  * via: https://github.com/twbs/bootstrap-rubygem
* fix issues with border-radius on input_groups
* fix input_group tests

/cc @mhw

### CODE REVIEW

**Comment by mhw** [comment]
Hi; what issue did you find with the `input_groups` rounded corners? The `.has-validation` class is [recommended](https://getbootstrap.com/docs/5.0/forms/validation/#server-side) now to get rounded corners when a field can have validation feedback. Without it invalid fields get square corners on the right-hand end:

image

There _is_ an issue with the static HTML `input_groups` form: the input elements have square right-hand ends. That's a [reported issue](https://github.com/twbs/bootstrap/issues/25110#issuecomment-809869074) so I thought it better to have the markup be what it should be (in theory) for the moment in the hope the issue will be fixed. It's not an issue for `simple_form` generated markup though as it never generates a `.valid-feedback` element.

**Comment by m5o** [comment]
On the blank form, you see rounded corners on the prepend `.input-group-text` when the `.has-validation`-class *is* included. 

Yes, I've noticed the issues with validation feedback but primarily wanted visual parity with the style on the bootstrap documentation.
Check out the examples, https://getbootstrap.com/docs/5.0/forms/input-group/

Screenshot 2021-05-21 at 16 53 53

**Comment by mhw** [comment]
Ah, right - I see what you mean. I'd not noticed that previously.

Looking back at the bootstrap PR I think the intention is that `.has-validation` is only added when there's a `<div class="invalid-feedback">` (or `valid-feedback`). Do you know if that's something `simple_form` can do?

**Comment by m5o** [comment]
As far as I know, there is no way in SF to add additional CSS classes to the parent wrapper if there is an error on the input field.

**Pull request merged**
