### PR TITLE
Bootstrap 5 updates

### LINKED ISSUE #323: bootstrap 5 dropped .form-group
https://getbootstrap.com/docs/5.0/migration/#forms-2

### PR DESCRIPTION
**Pull request by mhw**
I wanted to get Simple Form working with Bootstrap 5 for a new application I'm working on. To make sure I did a complete job I've updated the example application as it seems to cover most of the form variants. This PR contains the updates I've made to get things working.

I'm not sure how you might want to handle the release of Bootstrap 5: while I'm sure there'll be some demand for Simple Form being updated when Bootstrap 5 ships, I imagine continued support for Bootstrap 4 will be needed for a while too. As the Bootstrap assets are pulled in to this app as a gem dependency it would be tricky to support both versions from one instance of the app. Perhaps a second instance of the app could be deployed, but that might mean keeping the `master` and `bootstrap-5` branches separate.

Similarly, when adding this to the `simple_form` gem it might be worth keeping the generator for Bootstrap 4, at least for a while.

Key points:

* Bootstrap 5 drops the `.custom-*` styles as they've been largely merged into the `.form-*` ones. I've dropped the custom form sample and the chunk of the initializer that implements it.

* Floating label support is now built in, so I've converted the example to use the Bootstrap 5 classes and removed `_form_floating_labels.scss`. Selects with `multiple` aren't supported though, so I've removed that from the example.

* Input groups with validation feedback need a `.has-validation` class and the feedback pulled inside the input group. This works fine for the Simple Form generated markup as it will only create a single `.invalid-feedback` element. The HTML in `app/views/examples/input_groups/_bootstrap.html.erb` has both `.invalid-feedback` and `.valid-feedback` elements, and loses the rounded end on the input group - see https://github.com/twbs/bootstrap/pull/31953 and https://github.com/twbs/bootstrap/issues/25110#issuecomment-809869074. 

Still to do:

- [x] Review and update the documentation pages

Fixes #323

### CODE REVIEW

**Comment by m5o** [comment]
Hey 👋 @mhw Thank you for the awesome work!! Let me think about the process and structure and if it’s really necessary to maintain two instances (may just for a fixed time). 
Will inspect & review your PR in a few days, busy atm.

**Comment by m5o** [comment]
So, in the meantime Bootstrap released the final v5 🎉

@mhw - Could you check/verify if your PR includes possible last minute tweaks.
(Did not follow all the litte changes between v4/v5 this time)

**Comment by mhw** [comment]
Yep, good idea. Give me a day or so and I'll check if anything needs tweaking.

**Comment by mhw** [comment]
I've reviewed the diff between 5.0.0.beta2 and 5.0.0 and there are no changes to the form styling that need any tweaks. I've bumped the dependency and synced `application.scss` with the file in `bootstrap-rubygem`.

I'll have a look at the documentation and see what needs updating there.

**Review by m5o — APPROVED** [review]
✨ 10x Thank you @mhw 🥳

**Comment by m5o** [comment]
@mhw all kudos go to you 🙇‍♂️ 

would you like to create the official PR to `simple_form`? 

It's basically just the update of [`config/initializers/simple_form_bootstrap.rb`](https://github.com/heartcombo/simple_form/blob/master/lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb)
As I know from @carlosantoniodasilva there is no plan to support multiple bootstrap generator versions side-by-side.

**Comment by mhw** [comment]
Sure, I'll take a swing at that. Thanks!

**Comment by carlosantoniodasilva** [comment]
Thanks for the work @mhw and @m5o!

Yes, I think it's easier for SF if we just keep the most recent version of the initializer there, and point people via readme/docs/generator install readme to the v4 generator on the app here if that's what they need. (I'm assuming that most people setting up SF + Bootstrap would do on a new app and are likely going with v5 in that case.)

**Comment by olimart** [comment]
Thanks a lot @mhw 🙏

**Comment by m5o** [comment]
🔗 https://github.com/heartcombo/simple_form/pull/1738

**Pull request merged**
